name: Sync OneDrive Links

on:
  schedule:
    - cron: '*/30 * * * *'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Link from OneDrive
        run: |
          # Download the file
          curl -L "https://connectpolyu-my.sharepoint.com/:u:/g/personal/22039716r_connect_polyu_hk/IQAZukIl0xaGR7VDIkof354FAWYb1PV0A6s3wR8eCQcwbcs?e=bTS7Yf&download=1" -o rutdepth_link.json

      - name: DEBUG - Show Downloaded File Content
        run: |
          echo "================ FILE START ================"
          cat rutdepth_link.json
          echo ""
          echo "================ FILE END ================="

      - name: Update tools.json using Python
        run: |
          python3 -c "
          import json
          import os

          try:
              with open('rutdepth_link.json', 'r') as f:
                  # Try to load the JSON
                  link_data = json.load(f)
                  new_url = link_data.get('url', '')
                  print(f'Found URL: {new_url}')
          except json.JSONDecodeError as e:
              print(f'ERROR: The file is not valid JSON.')
              print(f'Python Error Details: {e}')
              exit(1)

          # Update the tools.json file
          if os.path.exists('tools.json'):
              with open('tools.json', 'r') as f:
                  tools_config = json.load(f)

              updated = False
              for tool in tools_config.get('tools', []):
                  if tool.get('id') == 'rutting':
                      if tool.get('link') != new_url:
                          tool['link'] = new_url
                          tool['buttonText'] = 'Launch Tool'
                          updated = True
                      break
              
              if updated:
                  with open('tools.json', 'w') as f:
                      json.dump(tools_config, f, indent=2)
          "

      - name: Commit and Push
        run: |
          git config --global user.name "Link Updater Bot"
          git config --global user.email "bot@github.com"
          rm rutdepth_link.json
          if [[ -n $(git status -s tools.json) ]]; then
            git add tools.json
            git commit -m "Auto-update Rutting Tool URL"
            git push
          fi
