name: Sync OneDrive Links

on:
  schedule:
    - cron: '*/30 * * * *' # Runs every 30 minutes
  workflow_dispatch: # Allows manual trigger

permissions:
  contents: write

jobs:
  update-json:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Download Link from OneDrive
        run: |
          # Download the file from OneDrive and save it as 'rutdepth_link.json'
          curl -L "https://connectpolyu-my.sharepoint.com/:u:/g/personal/22039716r_connect_polyu_hk/IQAZukIl0xaGR7VDIkof354FAWYb1PV0A6s3wR8eCQcwbcs?e=bTS7Yf&download=1" -o rutdepth_link.json

      - name: Update tools.json using Python
        run: |
          python3 -c "
          import json
          import os

          # 1. Load the new link from OneDrive file
          with open('rutdepth_link.json', 'r') as f:
              link_data = json.load(f)
              new_url = link_data.get('url', '')

          # 2. Load the existing tools.json
          if os.path.exists('tools.json'):
              with open('tools.json', 'r') as f:
                  tools_config = json.load(f)

              # 3. Find the 'rutting' tool and update its link
              updated = False
              for tool in tools_config.get('tools', []):
                  if tool.get('id') == 'rutting':
                      print(f'Updating Rutting Tool link to: {new_url}')
                      tool['link'] = new_url
                      tool['buttonText'] = 'Launch Tool' # Optional: Change button text automatically
                      updated = True
                      break
              
              # 4. Save the file back
              if updated:
                  with open('tools.json', 'w') as f:
                      json.dump(tools_config, f, indent=2)
          "

      - name: Commit and Push
        run: |
          git config --global user.name "Link Updater Bot"
          git config --global user.email "bot@github.com"
          
          # Remove the temporary downloaded file so it doesn't clutter repo
          rm rutdepth_link.json

          # Commit changes to tools.json if any
          if [[ -n $(git status -s tools.json) ]]; then
            git add tools.json
            git commit -m "Auto-update Rutting Tool URL from OneDrive"
            git push
          else
            echo "No changes needed."
          fi
